### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yamazaki-yuri** [yamazaki-yuri/tokyopicnic#44]
issueを作成しました。
ご確認のほど、よろしくお願いいたします。
[ProjectのURLはこちら](https://github.com/users/yamazaki-yuri/projects/2)

## 実装予定の機能(MVP)
- [ ] ユーザーセッション関連
  - [ ] 新規登録(devise)
  - [ ] ログイン機能(devise&Google認証)
  - [ ] admin権限のログイン
- [ ] ユーザーによる公園レポート投稿機能
- [ ] マイページから、公園投稿の編集
- [ ] ブックマーク機能
- [ ] adminでの公園の情報登録・編集機能
- [ ] 公園検索機能
- [ ] 公園ランダム選定機能

## 必要なページ
- [ ] トップページ
- [ ] ユーザー新規登録
- [ ] ログインページ
- [ ] パスワードリセット
- [ ] マイページ
- [ ] 公園新規投稿ページ
- [ ] admin公園一覧
- [ ] admin公園編集画面
- [ ] 公園検索(公園一覧)
- [ ] 公園詳細
- [ ] プロフィール編集
- [ ] 投稿詳細
- [ ] ランダム選定結果ページ

**Comment by tarakish** [comment]
Projectsにアクセスしましたが、カンバン・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。
![スクリーンショット 2024-04-27 16 21 44](https://github.com/yamazaki-yuri/tokyopicnic/assets/71510236/3b10793b-f9b5-468a-bcee-e457168e2704)

**Comment by yamazaki-yuri** [comment]
失礼いたしました。
リポジトリにprojectをリンクさせました。
再度ご確認をお願いいたします。

**Comment by tarakish** [comment]
確認できました。LGTMです！
MVPリリースに向けて開発頑張ってください！
